"""
security/output_scan.py — LLM response security scanner.

Every response generated by the LLM passes through scan_output() before being
streamed to the user.

Detects:
  - System prompt / instruction leaks
  - Developer message leaks
  - Internal config leaks
  - Chain-of-thought / reasoning trace leakage
  - Identity drift (bot claiming to be another AI)

If a violation is detected:
  1. The original response is replaced with a safe fallback.
  2. The incident is logged (caller is responsible for DB write).
  3. A structured result is returned so the caller can log + act.
"""
from __future__ import annotations

import re
from typing import TypedDict


class ScanResult(TypedDict):
    clean: bool
    reason: str | None   # None when clean
    safe_reply: str      # Original reply when clean; fallback when flagged


_SAFE_FALLBACK = (
    "I'm here to help with university courses, fees, eligibility, and admissions. "
    "What would you like to know?"
)

# ---------------------------------------------------------------------------
# Detection patterns
# ---------------------------------------------------------------------------

_LEAK_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("system_prompt_leak", re.compile(
        r"(here\s+is|my|the)\s+(system\s+prompt|instructions?|initial\s+prompt|rules?|guidelines?)", re.I
    )),
    ("system_prompt_leak", re.compile(
        r"(system\s+prompt|developer\s+instructions?|hidden\s+instructions?)\s*(says?|is|are|:)", re.I
    )),
    ("internal_instruction_leak", re.compile(
        r"(i\s+(was|am)\s+(told|instructed|programmed|trained)\s+to\s+(never|always|only))", re.I
    )),
    ("chain_of_thought_leak", re.compile(
        r"(<thinking>|</thinking>|\[thinking\]|\[reasoning\]|<scratchpad>)", re.I
    )),
    ("identity_drift", re.compile(
        r"(i\s+am\s+(chatgpt|gpt[-\s]?\d|claude|gemini|bard|openai|copilot))", re.I
    )),
    ("identity_drift", re.compile(
        r"(as\s+(chatgpt|gpt|claude|gemini),?\s+i)", re.I
    )),
    ("config_leak", re.compile(
        r"(api[_\s]key|secret[_\s]key|database[_\s]url|password)\s*[:=]", re.I
    )),
]


def scan_output(reply: str) -> ScanResult:
    """
    Scan an LLM-generated reply for security violations.

    Returns ScanResult with:
      clean=True  → safe_reply contains the original reply
      clean=False → safe_reply contains the fallback; reason names the violation
    """
    for reason, pattern in _LEAK_PATTERNS:
        if pattern.search(reply):
            return ScanResult(clean=False, reason=reason, safe_reply=_SAFE_FALLBACK)
    return ScanResult(clean=True, reason=None, safe_reply=reply)
